addons:
  firefox: "42.0"

language: java

jdk:
  - oraclejdk8

before_install:
  - pip install --user codecov
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_script:
  - ./gradlew copyPortalExt
  - ./gradlew setupTestableTomcat
  - ./liferay/liferay-ce-portal-7.0-ga3/tomcat-8.0.32/bin/startup.sh
  - tail -f ./liferay/liferay-ce-portal-7.0-ga3/tomcat-8.0.32/logs/catalina.out &
  - ./gradlew checkLiferay

script:
  - ./gradlew testIntegration
  - ls liferay

cache.directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/caches/
  - liferay